### ISSUE TITLE
请问readme最后的几张3D图是如何生成的呢

### ISSUE THREAD

**Issue by wqvbjhc** [KeeganRen/dlib_eos#1]
您好！请问readme最后的几张3D图是如何生成的呢。如下图。
 ![image](https://raw.githubusercontent.com/KeeganRen/FaceReconstruction/master/imgs/image.3dface2.png)

**Comment by punkhooren** [comment]
@wqvbjhc  可以看一下工程，或者用bin下的fit-model.
